### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by geniejhang** [KUNPL/KUThesis#1]
사실 Bibliography를 어떻게 써야하는지 아직 하나도 모릅니다.

모두의 정보를 모아봅시다!

**Comment by TaeHyunHwang** [comment]
저희같은 경우는 그냥 논문 맨 끝에 thebibliography 사용해요.

예제)

\begin{thebibliography}{25}

\bibitem{E}

\bibitem{JT}

\bibitem{KKP}

\end{thebibliography}

**Comment by geniejhang** [comment]
오오. 첫번째 컨트리뷰트 감사합니다!

지금은 natbib.sty와 IEEEbib.bst파일 두개를 가지고, library.bib 파일을 읽어서 bibtex을 실행시켰을 때,
thesis.tex을 컴파일하고 나온 aux파일을 자동으로 읽어서, 어떤 것들이 cite됐는지를 판단해가지고 자동으로
thebibliography 태그를 생성해주는 것 같습니다.

알아야 할 점은 natbib.sty와 IEEEbib.bst의 역할과, 이 둘이 맥의 Papers나 윈도우의 EndNote가 출력해주는
bibliography library 파일을 읽어와서 동작하느냐 인 것 같습니다.

안된다면, 적어도 시작으로는 이 두개의 프로그램에서는 되도록 개선하는게 좋을 것 같구요.

몇가지 스타일에 대한 예시를 찾아볼 수 있었습니다.
http://sites.stat.psu.edu/~surajit/present/bib.htm

**Comment by geniejhang** [comment]
PRL 기준입니다.

· 저널 이름, 볼륨 번호, 페이지, 연도 (번역 저널인 경우 원본과 번역에 대한 정보 포함)
· 컨퍼런스 이름 (혹은 주제), 장소, 연도, 편집자, 발행자, 발행년도
· 책 이름, 편집자, 발행자, 발행년도
· 보고서 발행 기관의 전체 이름과 보고서 식별번호

J. M. Smith, R. Brown, and C. Green, Phys. Rev. B **26**, 1 (1982); Nucl. Phys. **A195**, 1 (1982).
J. M. Smith, Phys. Rev. D (to be published); R. Brown, Phys. Rev. B **26**, 706(E) (1982).
J. M. Smith, Molecular Dynamics (Academic, New York, 1980), Vol. 20, p. 20.
R. Brown, in Charge Density Waves in Solids, edited by C. Green, Modern Problems in Condensed Matter Sciences Vol. 25 (North-Holland, Amsterdam, 1989).
C. Green, University of Wisconsin, Madison, Report No. MAD/PH/650, 1991.
J. M. Smith et al., in Proceedings of the Topical Meeting on CP Violation, Calcutta, June 1990 (unpublished).

원문

The reference should cite: journal name, volume number, page, and year (in the case of translation journals, give information for original and translation); conference name (or topic), place, year, editor(s), publisher, and year of publication; book title, editor(s), publisher, and year of publication; report issuing institution in full and identification number of the report (give title if number not available). Some examples of proper form follow (also consult recent issues of the journal).

J. M. Smith, R. Brown, and C. Green, Phys. Rev. B 26, 1 (1982); Nucl. Phys. A195, 1 (1982).
J. M. Smith, Phys. Rev. D (to be published); R. Brown, Phys. Rev. B 26, 706(E) (1982).
J. M. Smith, Molecular Dynamics (Academic, New York, 1980), Vol. 20, p. 20.
R. Brown, in Charge Density Waves in Solids, edited by C. Green, Modern Problems in Condensed Matter Sciences Vol. 25 (North-Holland, Amsterdam, 1989).
C. Green, University of Wisconsin, Madison, Report No. MAD/PH/650, 1991.
J. M. Smith et al., in Proceedings of the Topical Meeting on CP Violation, Calcutta, June 1990 (unpublished).

**Comment by geniejhang** [comment]
학교에서 뭘 원하는지 모르겠지만, apsrev4-1 스타일로 일단 고정해놨으며 IEEEtranN 버전도 사용할 수 있도록 일단 주석에 넣어뒀습니다.
library.bib 제작 방법을 따로 작성해야 될 것 같습니다.
또, 참고 논문이 어떤것인지 번호로 출력하게 바꾸었습니다.

참고자료:
http://en.wikibooks.org/wiki/LaTeX/Bibliography_Management

**Comment by geniejhang** [comment]
현재 버전은 제가 졸업논문을 쓸 때 사용한 버전이 들어가 있습니다.
bib파일 제작은 Mac papers를 사용했습니다.
