### ISSUE TITLE
XeLaTeX 컴파일 지원

### ISSUE THREAD

**Issue by rohnugu** [KUNPL/KUThesis#14]
안녕하세요. 
공개해주신 코드를 베이스로 박사학위 논문 작성에 사용하려고 합니다.
석사 논문은 다른 학교 LaTeX 파일을 대충 수정해 작성했는데
이렇게 잘 만든 cls로 논문을 작성할 수 있게 된 점 감사드립니다.

다름이 아니라 저는 PDFLaTeX가 아니라 XeLaTeX를 사용하는데,
컴파일이 안 되서 소스 코드를 검토해보니
cls 파일에 영문 커맨드와 CJK 문자가 이어져 있는 일부가 제대로 파싱이 안 되서 그렇더라고요.
이 문제를 해결하기 위해서는 아래와 같이 해당 커맨드를 중괄호로 감싸면 될 것 같습니다.

498: \fontsize{16pt}{16pt}\selectfont{\bf {\@degreeChn}士學位 論文으로 提出함}
501: \fontsize{16pt}{16pt}\selectfont{\bf 이 論文을 \@degreeName{ }{\@degreeChn}士學位 論文으로 提出함}
504: \fontsize{14pt}{14pt}\selectfont{\bf {\@submitYear}年\ {\@submitMonth}月\ {\@submitDay}日}
532: \fontsize{15.5pt}{15.5pt}\selectfont{\bf {\@authorChn}의 \@degreeName{ }{\@degreeChn}士學位論文 審査를 完了함}
534: \fontsize{14pt}{14pt}\selectfont{\bf {\@submitYear}年\ {\@submitMonth}月\ {\@submitDay}日}

**Comment by geniejhang** [comment]
리포트 감사합니다~
업데이트 완료했습니다.
