### ISSUE TITLE
이 템플릿 그대로 사용해도 도서관에서 받아주는지 궁금합니다!

### ISSUE THREAD

**Issue by becxer** [KUNPL/KUThesis#15]

**Comment by geniejhang** [comment]
2016년 8월 졸업용 제출본으로는 문제 없었습니다
그 이후에 규정이 바뀌지 않았다면 계속 사용 가능합니다.

**Comment by becxer** [comment]
@geniejhang 와, 빠른 답변 정말 감사드립니다! 

 [https://library.korea.ac.kr/link/html/useThesesGuide03](https://library.korea.ac.kr/link/html/useThesesGuide03)
여기 Readme 에 언급된 링크의 제약사항과 다른점이 있어서, 몇가지 추가 의문점이 있습니다.

1. 도서관 양식의 대제목, 중제목, 소제목 등의 폰트 크기랑 Latex템플릿으로 만든 크기랑 다르게 나오던데요. (예를 들면 Chapter Introduction 의 폰트크기는 제목보다 크다거나) 이것도 도서관에서 크게 상관하지는 않나요? 

2. 템플릿에 보면 abstract가 심사검인서랑 목차 사이에 나오던데요.  이것도 도서관에서 크게 상관하지는 않나요?

3. 2016년도랑 지금은 규정이 같긴 합니다. 전체적으로 도서관에서 그렇게 엄격하게 검사를 하지 않는걸까요..? 만약 안된다면, 수십개의 equation 을 워드로 다시 작성 해야 할지도 모르는 상황이... ㅠㅠ 

4. 혹시 가능하시다면... 도서관 제출에 성공 하셨던 latex 파일을 이메일로 받아서 참고 할수 있거나 제출하셨던 논문을 제가 도서관에서 찾아볼 수 있을런지요..? 제 이메일은 whitewest87@gmail.com 입니다.

도움 주셔서 정말 감사드립니다!

**Comment by becxer** [comment]
2019년도 2월 졸업 용으로도 가능합니다. 

감사합니다!
